### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mbenz89** [michalrus/git-hooks-code-autoformat#12]
Hi,

I am a maintainer of the [Soot Java optimization framework](https://github.com/sable/soot).
We are currently discussing the usage of your tool to enforce coding guidelines. However, I am not sure if we are allowed to do so since Soot is licensed under LGPLv2.1. As far as I know, it is incompatible with Apache 2.0. I am not sure if we might still be able to use is without directly accessing the source code and not shipping it in our repo, though. On the other hand, your current way of deployment requires including the tool into our repository.

Do you know if we would be able to incorporate it without licensing issues? If not, is there any change you might double license it to LGPLv2.1 sometime?

I would also like to know if you are making progress with your known issue of adding, modifying and committing some files?

Manuel

**Comment by michalrus** [comment]
Hey, Manuel.

I’m happy you were able to resolve the issue.

For any future readers:

> Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.
>
> — https://www.apache.org/licenses/GPL-compatibility.html
