### ISSUE TITLE
unable commit becouse is error: Could not find or load main class ejf.Main

### ISSUE THREAD

**Issue by krzpob** [michalrus/git-hooks-code-autoformat#19]
I think that binary should be included, or link for download should be provided.

**Comment by michalrus** [comment]
The binary is being built when the autoformatter is first run.

The source is https://github.com/michalrus/git-hooks-code-autoformat/blob/9ca6afd1a64c9a476084c043b8ce0878389afc39/tools/eclipse-java-formatter/src/ejf/Main.java

You sure you didn’t change any of the autoformatter code?

**Comment by sbweeden** [comment]
How precisely does this automatic build of the elf formatter happen?

**Comment by michalrus** [comment]
No further info.
