### ISSUE TITLE
Could I only format changed lines by this tool?

### ISSUE THREAD

**Issue by acearth** [michalrus/git-hooks-code-autoformat#5]
This means,  if I changed some lines in one file, I don't want to format all lines in this file. I just want to format the lines changed by me. If all lines has been formatted, GIT BLAME will pointed to me!

**Comment by michalrus** [comment]
Well, it would certainly be best to format all of the project in one commit, and make everybody else use the autoformatter. :smiley_cat: 

The problem with this suggestion is that not all autoformatters we’re using can format arbitrary chunks of the files… I’d even say most cannot. Consider this diff:

```diff
diff --git a/x.xml b/x.xml
index 6ff7324..26c7d9b 100644
--- a/x.xml
+++ b/x.xml
@@ -1,5 +1,5 @@
 <a>
-  <b>
-    c
+  <b attr="val">
+    d
   </b>
 </a>
```

Do we just pass the `+` lines to the autoformatter? Which would parse just this fragment? None, I guess. =)

**Comment by markh-de** [comment]
Even worse: Consider adding another level around the old **c** (refering to your diff above). Then your unchanged line containing the **c** would need to be indented by one more level. But it would be invisible to the indenter if you only pass changed lines. Short: The indenter always needs to know the full context of the part it is about to indent.
Also, git blame will only point to you if the indenting process actually changes something. If you modify code and apply correct indenting (which you should do anyway) the effect is the same. Also, git blame should ignore whitespace changes, so changing a line's indent level will not count as "your" change.
